/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cascader: typeof import('./../src/components/VanFormBuilder/VanFormItems/Cascader.vue')['default']
    Checkbox: typeof import('./../src/components/VanFormBuilder/VanFormItems/Checkbox.vue')['default']
    Customize: typeof import('./../src/components/VanFormBuilder/VanFormItems/Customize.vue')['default']
    DatePicker: typeof import('./../src/components/VanFormBuilder/VanFormItems/DatePicker.vue')['default']
    Input: typeof import('./../src/components/VanFormBuilder/VanFormItems/Input.vue')['default']
    MultipleSelect: typeof import('./../src/components/VanFormBuilder/VanFormItems/MultipleSelect.vue')['default']
    PickerGroup: typeof import('./../src/components/VanFormBuilder/VanFormItems/PickerGroup.vue')['default']
    Radio: typeof import('./../src/components/VanFormBuilder/VanFormItems/Radio.vue')['default']
    Rate: typeof import('./../src/components/VanFormBuilder/VanFormItems/Rate.vue')['default']
    SDatePicker: typeof import('./../src/components/VanFormBuilder/Pickers/SDatePicker.vue')['default']
    Select: typeof import('./../src/components/VanFormBuilder/VanFormItems/Select.vue')['default']
    Slider: typeof import('./../src/components/VanFormBuilder/VanFormItems/Slider.vue')['default']
    SPicker: typeof import('./../src/components/VanFormBuilder/Pickers/SPicker.vue')['default']
    Stepper: typeof import('./../src/components/VanFormBuilder/VanFormItems/Stepper.vue')['default']
    STimePicker: typeof import('./../src/components/VanFormBuilder/Pickers/STimePicker.vue')['default']
    Switch: typeof import('./../src/components/VanFormBuilder/VanFormItems/Switch.vue')['default']
    TimePicker: typeof import('./../src/components/VanFormBuilder/VanFormItems/TimePicker.vue')['default']
    Uploader: typeof import('./../src/components/VanFormBuilder/VanFormItems/Uploader.vue')['default']
    VanCascader: typeof import('vant/es')['Cascader']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanFormBuilder: typeof import('./../src/components/VanFormBuilder/VanFormBuilder.vue')['default']
    VanFormItem: typeof import('./../src/components/VanFormBuilder/VanFormItem.vue')['default']
    VanMultiplePicker: typeof import('./../src/components/VanFormBuilder/ExtComps/VanMultiplePicker/VanMultiplePicker.vue')['default']
    VanPicker: typeof import('vant/es')['Picker']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
